### ISSUE TITLE
Project Description 

### ISSUE THREAD

**Issue by skmorgane** [weecology/MATSS-startup#26]
- [x] Introduction
- [x] Aim 1
- [x] Aim 2
- [x] Aim 3
- [x] Figure Aim 1
- [x] Figure Aim 2
- [x] Figure Aim 3
- [x] Intellectual Merit
- [x] Broader Impacts
- [x] Project Mangement Plan
- [x] Project Management table
- [x] Prior support
   - [x] White
   - [x] Ernest
   - [x] Ye

**Comment by ethanwhite** [comment]
Full draft complete
